const TOKEN_TAG = 'TOKEN_TAG';
const FILES_TAG = 'FILES_TAG';
const BRANCHES_TAG = 'BRANCHES_TAG';
const BRANCH_TAG = 'BRANCH_TAG';
const EMPLOYEE_CATEGORY_TAG = 'EMPLOYEE_CATEGORY_TAG';
const EMPLOYEES_TAG = 'EMPLOYEES_TAG';
const BRANCH_CODES_TAG = 'BRANCH_CODES_TAG';

const ALL_TAGS = [
	TOKEN_TAG,
	FILES_TAG,
	BRANCHES_TAG,
	BRANCH_TAG,
	EMPLOYEE_CATEGORY_TAG,
	EMPLOYEES_TAG,
	BRANCH_CODES_TAG,
];

export {
	ALL_TAGS,
	TOKEN_TAG,
	FILES_TAG,
	BRANCHES_TAG,
	BRANCH_TAG,
	EMPLOYEE_CATEGORY_TAG,
	EMPLOYEES_TAG,
	BRANCH_CODES_TAG,
};
