import { ADAPTER_ROUTES_BREADCRUMBS, ROUTES } from '~~>shared/model/routes';

const NAV_DATA = [
	{
		id: 1,
		text: ADAPTER_ROUTES_BREADCRUMBS[ROUTES.MY_APPLICATIONS_All],
		path: ROUTES.MY_APPLICATIONS_All,
	},
	{
		id: 2,
		text: ADAPTER_ROUTES_BREADCRUMBS[ROUTES.MY_APPLICATIONS_ACTIVE],
		path: ROUTES.MY_APPLICATIONS_ACTIVE,
	},
	{
		id: 3,
		text: ADAPTER_ROUTES_BREADCRUMBS[ROUTES.MY_APPLICATIONS_COMPLETED],
		path: ROUTES.MY_APPLICATIONS_COMPLETED,
	},
];

export { NAV_DATA };
