const MAX_VISIBLE_PAGES = 3;
const HALF_VISIBLE = Math.floor(MAX_VISIBLE_PAGES / 2);
const PAGE_WINDOW_OFFSET = MAX_VISIBLE_PAGES - 1;
const GAP_LEFT_THRESHOLD = MAX_VISIBLE_PAGES - HALF_VISIBLE;
const LEFT_REMAINS = GAP_LEFT_THRESHOLD - HALF_VISIBLE;
const GAP_RIGHT_THRESHOLD = GAP_LEFT_THRESHOLD - 1;
const RIGHT_REMAINS = 1;

export {
	MAX_VISIBLE_PAGES,
	HALF_VISIBLE,
	PAGE_WINDOW_OFFSET,
	GAP_LEFT_THRESHOLD,
	LEFT_REMAINS,
	GAP_RIGHT_THRESHOLD,
	RIGHT_REMAINS,
};
